// src/routes/(protected)/chats/[chatId]/messages/+page.svelte
<script lang="ts">
	import { processStreamResponse } from '$lib/processors/stream-processor';
	import { onMount, tick } from 'svelte';
    import type { PageData, RouteParams } from '../../../../chats/[chatId]/messages/$types';
	import type { IMessage } from '$lib/types/message';
	import ChatMessages from '$lib/components/messages/ChatMessages.svelte';
	import { DatalabAPI } from '$lib/apis/datalab-api';
	import { MessageSchema } from '$lib/validators/messages';

    let { params }: { data: PageData, params: RouteParams } = $props();

    let messages = $state<IMessage[]>([]);
    let messagesOnStreaming = $state<IMessage[]>([]);
    let mapMessagesByRole = new Map<string, IMessage>();

    onMount(async () => {
        const historicalMessages = await DatalabAPI.ChatsResource.getChatMessages(Number(params.chatId));
        processStreamResponse(
            historicalMessages,
            (historicalMessages: IMessage[]) => { messages.push(...historicalMessages) }
        );
    });

    const scrollToBottom = async () => {
        await tick();
        const conversationElement = document.getElementById('conversation-container');
        if (conversationElement) {
            conversationElement.scrollTo({
                top: conversationElement.scrollHeight,
                behavior: 'smooth'
            });
        }
    };

    const streamingMessages = async (newMessages: IMessage[]) => {
        console.log("streamingMessage", newMessages);

        const lastRole = newMessages[newMessages.length - 1]?.role;
        mapMessagesByRole.set(lastRole, newMessages[newMessages.length - 1]);

        let allNewMessages = Array.from(mapMessagesByRole.values());
        messagesOnStreaming = allNewMessages;
    }

    const streamingCompleted = async () => {
        console.log("streamingCompleted");
        messages.push(...messagesOnStreaming);
        messagesOnStreaming = [];
        mapMessagesByRole.clear();
    }

    const handleMessageSubmit = async (event: Event) => {
        event.preventDefault();
        const form = event.target as HTMLFormElement;
        const formData = new FormData(form);
        const userPrompt = String(formData.get('userInput')).trim();
        form.reset();

        try {
            MessageSchema.parse({ message: userPrompt });
            const response = await DatalabAPI.ChatsResource.sendMessage(Number(params.chatId), userPrompt);
            await processStreamResponse(
                response,
                streamingMessages,
                streamingCompleted
            );
            await scrollToBottom();
        } catch (e) {
            console.error('There was a problem with the fetch operation:', e);
        }
    };


</script>


<h1>Chat ID: {params.chatId}</h1>

<h2>Messages ({messages.length}):</h2>

<div id="conversation-container" class="conversation">
    {#if messages.length === 0}
        <h5>💬 Nenhuma mensagem ainda</h5>
        <p>Comece uma conversa digitando sua pergunta abaixo!</p>
    {:else}
        {#each messages as message }
            <ChatMessages message={message} />
        {/each}
    {/if}

    {#if messagesOnStreaming.length > 0}
        {#each messagesOnStreaming as messageOnStreaming }
            <ChatMessages message={messageOnStreaming} />
        {/each}
    {/if}

</div>

<div class="max-w-4xl mx-auto px-4 sm:px-6">
    <form method="post" onsubmit={handleMessageSubmit} class="flex gap-3 items-stretch py-5">
        <label for="userInput" class="flex-1">
            <input 
                type="text" 
                id="userInput"
                name="userInput" 
                placeholder="Digite sua mensagem..." 
                required 
                minlength="4"
                autocomplete="off"
                class="
                    w-full px-5 py-3 text-base
                    border-2 border-gray-200 rounded-full
                    outline-none transition-all bg-gray-50
                    focus:border-purple-500 focus:bg-white 
                    focus:ring-4 focus:ring-purple-100
                    placeholder:text-gray-400
                "
            />
        </label>
        <button 
            type="submit"
            aria-label="Enviar mensagem"
            class="
                flex items-center justify-center
                w-12 h-12 
                bg-gradient-to-br from-purple-500 to-purple-700
                border-none rounded-full text-white
                cursor-pointer transition-all
                hover:scale-105 hover:shadow-lg hover:shadow-purple-400/50
                active:scale-95
                disabled:opacity-50 disabled:cursor-not-allowed 
                disabled:hover:scale-100
            "
        >
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <line x1="22" y1="2" x2="11" y2="13"></line>
                <polygon points="22 2 15 22 11 13 2 9 22 2"></polygon>
            </svg>
        </button>
    </form>
</div>

<style lang="postcss">
  @reference "tailwindcss";

  .conversation {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    padding: 1.5rem;
    margin-bottom: 1rem;
    max-height: 600px;
    overflow-y: auto;
    background: linear-gradient(to bottom, #f9fafb, #ffffff);
    border-radius: 12px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
    scroll-behavior: smooth;
  }

  .conversation::-webkit-scrollbar {
    width: 8px;
  }

  .conversation::-webkit-scrollbar-track {
    background: #f1f1f1;
    border-radius: 10px;
  }

  .conversation::-webkit-scrollbar-thumb {
    background: #c1c1c1;
    border-radius: 10px;
  }

  .conversation::-webkit-scrollbar-thumb:hover {
    background: #a8a8a8;
  }

  /* Mensagem vazia */
  .conversation h5 {
    text-align: center;
    color: #6b7280;
    font-size: 1.25rem;
    margin-bottom: 0.5rem;
  }

  .conversation p {
    text-align: center;
    color: #9ca3af;
    font-size: 0.95rem;
  }

  /* Responsividade */
  @media (max-width: 768px) {
    .conversation {
      padding: 1rem;
    }
  }

</style>

// src/components/Chat-Messages/messages.tsx
import { useEffect, useState, useRef, useCallback } from 'react';
import { marked } from 'marked';
import { DatalabAPI, processStreamResponse, type IMessage } from '../../services/datalab-api';

interface IMessagesHistoryProps {
    chatId: number;
    onError: (error: unknown) => void;
}

export const Messages = ({ chatId, onError }: IMessagesHistoryProps) => {
    const conversationRef = useRef<HTMLDivElement>(null);
    const mapMessagesByRole = useRef(new Map<string, IMessage>());

    const [messages, setMessages] = useState<IMessage[]>([]);
    const [messagesOnStreaming, setMessagesOnStreaming] = useState<IMessage[]>([]);
    const [isDisabled, setIsDisabled] = useState(false);
    const [isLoading, setIsLoading] = useState(false);
    const [prompt, setPrompt] = useState('');

    const streamingMessage = async (newMessages: IMessage[]) => {
        console.log("streamingMessage", newMessages);

        const lastRole = newMessages[newMessages.length - 1]?.role;
        mapMessagesByRole.current.set(lastRole, newMessages[newMessages.length - 1]);

        const allNewMessages = Array.from(mapMessagesByRole.current.values());
        setMessagesOnStreaming(allNewMessages);
    }

    const streamingCompleted = async () => {
        console.log("streamingCompleted");
        setMessagesOnStreaming((streamedMessages) => {
            const combinedMessages = [...messages, ...streamedMessages];
            setMessages(combinedMessages);
            return [];
        })
        mapMessagesByRole.current.clear();
    }

    const handleError = useCallback((error: unknown) => {
        console.error(error);
        onError(error);
        setIsDisabled(false);
        setIsLoading(false);
    }, [onError]);

    const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        setIsLoading(true);

        const currentPrompt = prompt;
        setPrompt('');
        setIsDisabled(true);

        DatalabAPI.sendMessage(Number(chatId), currentPrompt).
            then(async stream => {
                await processStreamResponse(stream, streamingMessage, streamingCompleted);
                setIsLoading(false);
                setIsDisabled(false);
            }).catch(error => {
                handleError(error);
            });
    };

    useEffect(() => {
        const fetchMessages = () => {
            DatalabAPI.getChatMessages(chatId).
                then(async stream => {
                    await processStreamResponse(stream, (newMessages) => {setMessages([...newMessages])});
                }).catch(error => {
                    handleError(error);
                });
        };
        fetchMessages();
    }, [chatId, handleError]);

    // Auto-scroll to bottom when new messages arrive
    useEffect(() => {
        if (conversationRef.current) {
            conversationRef.current.scrollTop = conversationRef.current.scrollHeight;
        }
    }, [messages, messagesOnStreaming]);

    return (
        <div>
            <div id="conversation" ref={conversationRef}>
                {messages.length === 0 ? (
                    <div className="text-center text-muted py-5">
                        <h5>💬 Nenhuma mensagem ainda</h5>
                        <p>Comece uma conversa digitando sua pergunta abaixo!</p>
                    </div>
                ) : (
                    messages.map((message, index) => (
                        <div
                            key={index}
                            className={`${message.role}`}
                            title={`${message.role} em ${new Date(message.timestamp).toLocaleString('pt-BR')}`}
                            dangerouslySetInnerHTML={{
                                __html: message.content ? marked.parse(message.content) : ''
                            }}
                        />
                    ))
                )}
                {messagesOnStreaming.length > 0 ?
                    messagesOnStreaming.map((message, index) => (
                        <div 
                            key={index}
                            className={`${message.role}`}
                            title={`${message.role} em ${new Date(message.timestamp).toLocaleString('pt-BR')}`}
                            >{message.content}</div>
                    )) : null
                }
            </div>
            {isLoading && (
                <div className="d-flex justify-content-center mb-3">
                    <div className={`spinner ${isLoading ? 'active' : ''}`} />
                        <p className="text-muted ms-3 align-self-center">
                            <em>IA está pensando...</em>
                        </p>
                </div>
            )}

            <form onSubmit={handleSubmit}>
                <div className="d-flex gap-2 align-items-end">
                    <div className="flex-grow-1">
                        <input
                            id="prompt-input"
                            name="prompt"
                            className="form-control"
                            value={prompt}
                            onChange={(e) => setPrompt(e.target.value)}
                            disabled={isDisabled}
                            placeholder="Digite sua mensagem aqui..."
                            onKeyDown={(e) => {
                                if (e.key === 'Enter' && !e.shiftKey && !isDisabled && prompt.trim()) {
                                    e.preventDefault();
                                    const form = e.currentTarget.closest('form');
                                    if (form) {
                                        const submitEvent = new Event('submit', { bubbles: true, cancelable: true });
                                        form.dispatchEvent(submitEvent);
                                    }
                                }
                            }}
                        />
                    </div>
                    <button
                        className="btn btn-primary"
                        type="submit"
                        disabled={isDisabled || !prompt.trim()}
                    >
                        {isLoading ? (
                            <>
                                <span className="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>
                                Enviando...
                            </>
                        ) : (
                            <>
                                <i className="bi bi-send me-1"></i>
                                Enviar
                            </>
                        )}
                    </button>
                </div>
            </form>
        </div>
    )
}
