// src/routes/chats/[chatId]/messages/+page.svelte
<script lang="ts">
	import { processStreamResponse } from '$lib/processors/stream-processor';
	import { onMount } from 'svelte';
    import type { PageData, RouteParams } from './$types';
	import type { IMessage } from './interfaces';

    let { data, params }: { data: PageData, params: RouteParams } = $props();

    let { loadInitialMessages } = data;
    let messages = $state<IMessage[]>([]);
    let messagesOnStreaming = $state<IMessage[]>([]);
    let mapMessagesByRole = new Map<string, IMessage>();

    onMount(async () => {
        let historicalMessages = await loadInitialMessages();
        console.log("Loaded messages:", historicalMessages);
        processStreamResponse(
            historicalMessages,
            (historicalMessages: IMessage[]) => { messages.push(...historicalMessages) }
        );
    });

    const streamingMessages = async (newMessages: IMessage[]) => {
        console.log("streamingMessage", newMessages);

        const lastRole = newMessages[newMessages.length - 1]?.role;
        mapMessagesByRole.set(lastRole, newMessages[newMessages.length - 1]);

        const allNewMessages = Array.from(mapMessagesByRole.values());
        console.log("allNewMessages", allNewMessages);
        messagesOnStreaming.push(...allNewMessages);
    }

    const streamingCompleted = async () => {
        console.log("streamingCompleted");
        messages.push(...messagesOnStreaming);
        messagesOnStreaming = [];
        mapMessagesByRole.clear();
    }

    const handleMessageSubmit = async (event: Event) => {
        event.preventDefault();
        const form = event.target as HTMLFormElement;
        const formData = new FormData(form);
        const userInput = String(formData.get('userInput')).trim();

        try {
            const response = await fetch('', {
                method: 'POST',
                body: JSON.stringify({ prompt: userInput }),
                headers: { 'Content-Type': 'application/json' },
            })
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            await processStreamResponse(
                response.body,
                streamingMessages,
                streamingCompleted
            );
        } catch (e) {
            console.error('There was a problem with the fetch operation:', e);
        }
    };


</script>


<h1>Chat ID: {params.chatId}</h1>

<h2>Messages ({messages.length}):</h2>

<div class="conversation">
    {#if messages.length === 0}
        <h5>💬 Nenhuma mensagem ainda</h5>
        <p>Comece uma conversa digitando sua pergunta abaixo!</p>

    {:else}
        {#each messages as message }
            <div>{message.content}</div>
            <div>{message.role}</div>
            <div>{message.timestamp}</div>
        {/each}
    {/if}

    {#if messagesOnStreaming.length > 0}
        {#each messagesOnStreaming as messageOnStreaming }
            <div>{messageOnStreaming.content}</div>
            <div>{messageOnStreaming.role}</div>
            <div>{messageOnStreaming.timestamp}</div>
        {/each}
    {/if}

</div>

<hr/>

<form method="post" action="?/sendMessage" onsubmit={handleMessageSubmit}>
    <label for="userInput">
        <input type="text" name="userInput" placeholder="Digite sua mensagem" required minlength="4" />
    </label>
    <button type="submit">Enviar</button>
</form>

<button onclick={() => messages.push({ content: "aaa", role: 'user', timestamp: new Date().toString() })}>Add Message</button>

<hr/>

// src/components/Chat-Messages/messages.tsx
import { useEffect, useState, useRef, useCallback } from 'react';
import { DatalabAPI, processStreamResponse, type IMessage } from '../../services/datalab-api';

interface IMessagesHistoryProps {
    chatId: number;
    onError: (error: unknown) => void;
}

export const Messages = ({ chatId, onError }: IMessagesHistoryProps) => {
    const conversationRef = useRef<HTMLDivElement>(null);
    const mapMessagesByRole = useRef(new Map<string, IMessage>());

    const [messages, setMessages] = useState<IMessage[]>([]);
    const [messagesOnStreaming, setMessagesOnStreaming] = useState<IMessage[]>([]);
    const [isDisabled, setIsDisabled] = useState(false);
    const [isLoading, setIsLoading] = useState(false);
    const [prompt, setPrompt] = useState('');

    const streamingMessage = async (newMessages: IMessage[]) => {
        console.log("streamingMessage", newMessages);

        const lastRole = newMessages[newMessages.length - 1]?.role;
        mapMessagesByRole.current.set(lastRole, newMessages[newMessages.length - 1]);

        const allNewMessages = Array.from(mapMessagesByRole.current.values());
        setMessagesOnStreaming(allNewMessages);
    }

    const streamingCompleted = async () => {
        console.log("streamingCompleted");
        setMessagesOnStreaming((streamedMessages) => {
            const combinedMessages = [...messages, ...streamedMessages];
            setMessages(combinedMessages);
            return [];
        })
        mapMessagesByRole.current.clear();
    }

    const handleError = useCallback((error: unknown) => {
        console.error(error);
        onError(error);
        setIsDisabled(false);
        setIsLoading(false);
    }, [onError]);

    const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        setIsLoading(true);

        const currentPrompt = prompt;
        setPrompt('');
        setIsDisabled(true);

        DatalabAPI.sendMessage(Number(chatId), currentPrompt).
            then(async stream => {
                await processStreamResponse(stream, streamingMessage, streamingCompleted);
                setIsLoading(false);
                setIsDisabled(false);
            }).catch(error => {
                handleError(error);
            });
    };

    useEffect(() => {
        const fetchMessages = () => {
            DatalabAPI.getChatMessages(chatId).
                then(async stream => {
                    await processStreamResponse(stream, (newMessages) => {setMessages([...newMessages])});
                }).catch(error => {
                    handleError(error);
                });
        };
        fetchMessages();
    }, [chatId, handleError]);

    // Auto-scroll to bottom when new messages arrive
    useEffect(() => {
        if (conversationRef.current) {
            conversationRef.current.scrollTop = conversationRef.current.scrollHeight;
        }
    }, [messages, messagesOnStreaming]);

    return (
        <div>
            <div id="conversation" ref={conversationRef}>
                {messages.length === 0 ? (
                    <div className="text-center text-muted py-5">
                        <h5>💬 Nenhuma mensagem ainda</h5>
                        <p>Comece uma conversa digitando sua pergunta abaixo!</p>
                    </div>
                ) : (
                    messages.map((message, index) => (
                        <div
                            key={index}
                            className={`${message.role}`}
                            title={`${message.role} em ${new Date(message.timestamp).toLocaleString('pt-BR')}`}
                        >{message.content}</div>
                    ))
                )}
                {messagesOnStreaming.length > 0 ?
                    messagesOnStreaming.map((message, index) => (
                        <div 
                            key={index}
                            className={`${message.role}`}
                            title={`${message.role} em ${new Date(message.timestamp).toLocaleString('pt-BR')}`}
                            >{message.content}</div>
                    )) : null
                }
            </div>
            {isLoading && (
                <div className="d-flex justify-content-center mb-3">
                    <div className={`spinner ${isLoading ? 'active' : ''}`} />
                        <p className="text-muted ms-3 align-self-center">
                            <em>IA está pensando...</em>
                        </p>
                </div>
            )}

            <form onSubmit={handleSubmit}>
                <div className="d-flex gap-2 align-items-end">
                    <div className="flex-grow-1">
                        <input
                            id="prompt-input"
                            name="prompt"
                            className="form-control"
                            value={prompt}
                            onChange={(e) => setPrompt(e.target.value)}
                            disabled={isDisabled}
                            placeholder="Digite sua mensagem aqui..."
                            onKeyDown={(e) => {
                                if (e.key === 'Enter' && !e.shiftKey && !isDisabled && prompt.trim()) {
                                    e.preventDefault();
                                    const form = e.currentTarget.closest('form');
                                    if (form) {
                                        const submitEvent = new Event('submit', { bubbles: true, cancelable: true });
                                        form.dispatchEvent(submitEvent);
                                    }
                                }
                            }}
                        />
                    </div>
                    <button
                        className="btn btn-primary"
                        type="submit"
                        disabled={isDisabled || !prompt.trim()}
                    >
                        {isLoading ? (
                            <>
                                <span className="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>
                                Enviando...
                            </>
                        ) : (
                            <>
                                <i className="bi bi-send me-1"></i>
                                Enviar
                            </>
                        )}
                    </button>
                </div>
            </form>
        </div>
    )
}
